/*
 * This source file was generated by the Gradle 'init' task
 */
package quantum.app

import quantum.complex.CartesianComplex
import quantum.complex.plus
import quantum.simple.complex.SimpleComplexCalculator

fun main() {
    val complex1 = CartesianComplex(1.0, 2.0)
    val complex2 = CartesianComplex(3.0, 4.0)

    val complexCalculator = SimpleComplexCalculator()
    val result = complexCalculator.calculate(complex1 + complex2)
    println("Complex 1: ${complex1}")
    println("Complex 2: ${complex2}")
    println("Sum: ${result}")
}
